In [100]:
# Importação das bibliotecas

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import mutual_info_regression
from sklearn.feature_selection import SelectKBest
from joblib import dump

# Carga, agrupamento e união dos dados meteorológicos e de produção

In [5]:
# Importação dos arquivos CSV dos dados meteorológicos e de produção

file = 'C:/Users/*******/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados_Meteorológicos.csv'
file2 = 'C:/Users/********/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados_Produção.csv'
df_meteo = pd.read_csv(file, sep = ';')
df_prod = pd.read_csv(file2, sep = ';')

In [6]:
 # Exibição dos dados meteorológicos
    
df_meteo.head()

,Unnamed: 0,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)",SAFRA
0,0,2009-05-01,0.0,910.0,9.7,20.9,13.8,8.2,78.8,46.0,9.0,3.8,0,0,0,0.0,2010
1,1,2009-05-02,0.0,909.4,9.4,21.8,14.4,8.6,75.5,39.0,9.5,3.3,0,0,0,0.0,2010
2,2,2009-05-03,0.2,907.8,8.1,21.9,14.1,8.3,72.0,29.0,9.2,3.6,0,0,0,0.0,2010
3,3,2009-05-04,0.0,905.7,11.3,22.0,15.3,8.7,79.1,52.0,10.2,4.2,0,0,0,0.0,2010
4,4,2009-05-05,0.0,905.2,10.6,22.8,15.7,10.1,74.7,39.0,9.6,3.6,0,0,0,0.0,2010

In [7]:
# Seleciona as colunas dos dados meteorológicos que serão utilizadas na análise

df_meteo = df_meteo.iloc[:, 2:17]
    
df_meteo.head() # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)",SAFRA
0,0.0,910.0,9.7,20.9,13.8,8.2,78.8,46.0,9.0,3.8,0,0,0,0.0,2010
1,0.0,909.4,9.4,21.8,14.4,8.6,75.5,39.0,9.5,3.3,0,0,0,0.0,2010
2,0.2,907.8,8.1,21.9,14.1,8.3,72.0,29.0,9.2,3.6,0,0,0,0.0,2010
3,0.0,905.7,11.3,22.0,15.3,8.7,79.1,52.0,10.2,4.2,0,0,0,0.0,2010
4,0.0,905.2,10.6,22.8,15.7,10.1,74.7,39.0,9.6,3.6,0,0,0,0.0,2010

In [8]:
# Agrupamento dos dados meteorológicos por safra

df_meteo_group = df_meteo.groupby('SAFRA').agg({'PRECIPITACAO TOTAL, DIARIO (AUT)(mm)' : 'sum',
                               'PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)' : 'mean',
                               'TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MAXIMA, DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MEDIA, DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MINIMA, DIARIA (AUT)(°C)' : 'mean',
                               'UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)' : 'mean',
                               'UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)' : 'mean',
                               'VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)' : 'mean',
                               'VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)' : 'mean',
                               'QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)':'sum',
                               'QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)':'sum',
                               'QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)':'sum',
                               'PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)':'sum'})

df_meteo_group # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
SAFRA,,,,,,,,,,,,,,
2010,2422.5,905.926849,12.060548,21.772329,15.497808,11.196438,82.360274,54.569863,10.421096,3.509589,633,1921,193,1835.5
2011,1976.8,906.158356,11.604384,21.324658,15.077260,10.669589,81.966301,54.123288,10.240274,3.465205,559,1734,60,1472.7
2012,1685.8,906.425410,10.142623,20.571038,14.105464,9.581967,77.634973,49.573770,10.369672,3.517213,663,1231,185,785.2
2013,1467.6,906.799452,11.457808,22.260274,15.629863,10.924932,79.155616,48.783562,10.555068,3.508219,494,1715,150,1024.9
2014,1781.8,906.668767,11.637534,22.095068,15.562466,10.783288,80.611233,50.978082,10.764658,3.495342,601,1697,292,1173.8
2015,2260.0,906.958904,12.616986,22.083288,15.920548,11.641370,83.132329,54.791781,11.184384,3.270685,454,1858,125,1499.0
2016,2328.7,906.420765,13.030055,21.993443,16.069945,12.022678,84.302459,58.251366,10.169945,3.237978,248,1737,142,1612.1
2017,1599.4,906.918630,11.520274,21.466301,15.043562,10.534521,82.045205,52.101370,10.922740,3.132055,708,1855,115,1163.8
2018,1675.8,906.890685,12.417534,22.483562,16.074247,11.615616,81.825753,52.419178,11.497808,3.281370,325,1712,119,1144.0
2019,2086.0,906.963562,12.643288,21.936164,15.736438,11.450685,84.120548,56.032877,10.417808,2.977260,655,1836,205,1403.0
2020,1879.2,907.025956,11.806557,22.114208,15.330328,11.089891,78.015301,50.177596,9.838798,3.085519,425,1471,222,1378.8
2021,1919.9,906.347671,11.814247,22.384932,15.700822,10.937534,80.752877,50.463014,9.846301,3.042466,527,1565,113,1108.6

In [9]:
# Realização e visualização do ajuste das casas decimais dos dados

df_meteo_group['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'] = round(df_meteo_group['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'], 1)
df_meteo_group['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'] = round(df_meteo_group['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'], 1)
df_meteo_group['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'] = round(df_meteo_group['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'], 1)
df_meteo_group['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'] = round(df_meteo_group['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'], 1)
df_meteo_group['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'] = round(df_meteo_group['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'], 1)
df_meteo_group['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'] = round(df_meteo_group['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'], 1)
df_meteo_group['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'] = round(df_meteo_group['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'], 1)
df_meteo_group['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'] = round(df_meteo_group['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'], 1)
df_meteo_group['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'] = round(df_meteo_group['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'], 1)

df_meteo_group # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
SAFRA,,,,,,,,,,,,,,
2010,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
2011,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
2012,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
2013,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
2014,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
2015,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
2016,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
2017,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
2018,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
2019,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
2020,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
2021,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6

In [10]:
# Remoção do índice dos dados

df_meteo_group = df_meteo_group.reset_index()

df_meteo_group # Exibição dos dados

,SAFRA,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
0,2010,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
1,2011,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
2,2012,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
3,2013,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
4,2014,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
5,2015,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
6,2016,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
7,2017,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
8,2018,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
9,2019,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
10,2020,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
11,2021,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6

In [ ]:
# Exibição dos dados de produção

df_prod.head()

In [12]:
# Seleciona as colunas dos dados de produção que serão utilizadas na análise

df_prod = df_prod.iloc[:, 7:11]
df_prod.drop(["CALIBRE"], axis = 1, inplace = True)
    
df_prod.head() # Exibição dos dados

   QUANTIDADE_KG  SAFRA AGRUPAMENTO_TAMANHO
0          815.0   2010                 IND
1         6754.0   2010                   M
2         5477.0   2010                   M
3         3685.0   2010                   P
4         1517.0   2010                   P

In [13]:
# Agrupamento dos dados de produção por safra

df_prod_group = df_prod.groupby(['SAFRA', 'AGRUPAMENTO_TAMANHO']).agg({'QUANTIDADE_KG' : 'sum'})

df_prod_group # Exibição dos dados

                           QUANTIDADE_KG
SAFRA AGRUPAMENTO_TAMANHO
2010  G                      11343372.00
      IND                     5756843.70
      M                       9258368.00
      OUTROS                  1121646.40
      P                       3110978.00
2011  G                      10700467.00
      IND                     5563779.00
      M                      10549548.00
      OUTROS                   944699.00
      P                       5225163.00
2012  G                       9501618.00
      IND                     4867309.00
      M                       9804192.00
      OUTROS                  1519227.00
      P                       6465573.09
2013  G                       5145363.10
      IND                     6793190.50
      M                      15145697.00
      OUTROS                   977978.20
      P                      16007880.00
2014  G                       5166052.00
      IND                     6273227.73
      M                      12692373.00
      OUTROS                   377336.70
      P                       9704383.10
2015  G                      12211695.61
      IND                     6607217.22
      M                      18727187.48
      OUTROS                   838831.11
      P                       9375881.11
2016  G                       8671974.30
      IND                    10877083.00
      M                      20090408.90
      OUTROS                   465380.00
      P                      16429474.00
2017  G                      19408151.29
      IND                     5837368.80
      M                      14680425.50
      OUTROS                   666907.00
      P                       3364829.00
2018  G                       8424341.00
      IND                     8707065.10
      M                      22282487.55
      OUTROS                  1155706.00
      P                      20328977.82
2019  G                      14500012.42
      IND                     5730985.47
      M                      20449473.19
      OUTROS                   542250.00
      P                      10570722.60
2020  G                       3474763.00
      IND                     7715875.00
      M                      18390288.21
      OUTROS                   516340.00
      P                      24493976.44
2021  G                      15137003.14
      IND                     6858814.00
      M                      25633907.28
      OUTROS                   483845.00
      P                      14108126.21

In [14]:
# Remoção do índice dos dados

df_prod_group = df_prod_group.reset_index()

df_prod_group # Exibição dos dados

    SAFRA AGRUPAMENTO_TAMANHO  QUANTIDADE_KG
0    2010                   G    11343372.00
1    2010                 IND     5756843.70
2    2010                   M     9258368.00
3    2010              OUTROS     1121646.40
4    2010                   P     3110978.00
5    2011                   G    10700467.00
6    2011                 IND     5563779.00
7    2011                   M    10549548.00
8    2011              OUTROS      944699.00
9    2011                   P     5225163.00
10   2012                   G     9501618.00
11   2012                 IND     4867309.00
12   2012                   M     9804192.00
13   2012              OUTROS     1519227.00
14   2012                   P     6465573.09
15   2013                   G     5145363.10
16   2013                 IND     6793190.50
17   2013                   M    15145697.00
18   2013              OUTROS      977978.20
19   2013                   P    16007880.00
20   2014                   G     5166052.00
21   2014                 IND     6273227.73
22   2014                   M    12692373.00
23   2014              OUTROS      377336.70
24   2014                   P     9704383.10
25   2015                   G    12211695.61
26   2015                 IND     6607217.22
27   2015                   M    18727187.48
28   2015              OUTROS      838831.11
29   2015                   P     9375881.11
30   2016                   G     8671974.30
31   2016                 IND    10877083.00
32   2016                   M    20090408.90
33   2016              OUTROS      465380.00
34   2016                   P    16429474.00
35   2017                   G    19408151.29
36   2017                 IND     5837368.80
37   2017                   M    14680425.50
38   2017              OUTROS      666907.00
39   2017                   P     3364829.00
40   2018                   G     8424341.00
41   2018                 IND     8707065.10
42   2018                   M    22282487.55
43   2018              OUTROS     1155706.00
44   2018                   P    20328977.82
45   2019                   G    14500012.42
46   2019                 IND     5730985.47
47   2019                   M    20449473.19
48   2019              OUTROS      542250.00
49   2019                   P    10570722.60
50   2020                   G     3474763.00
51   2020                 IND     7715875.00
52   2020                   M    18390288.21
53   2020              OUTROS      516340.00
54   2020                   P    24493976.44
55   2021                   G    15137003.14
56   2021                 IND     6858814.00
57   2021                   M    25633907.28
58   2021              OUTROS      483845.00
59   2021                   P    14108126.21

In [15]:
# União dos dados meteorológicos e de produção

df_merge = pd.merge(df_prod_group, df_meteo_group, how = 'outer', on = 'SAFRA').sort_values(by = 'SAFRA')

df_merge # Exibição dos dados

,SAFRA,AGRUPAMENTO_TAMANHO,QUANTIDADE_KG,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
0,2010,G,11343372.00,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
1,2010,IND,5756843.70,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
2,2010,M,9258368.00,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
3,2010,OUTROS,1121646.40,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
4,2010,P,3110978.00,2422.5,905.9,12.1,21.8,15.5,11.2,82.4,54.6,10.4,3.5,633,1921,193,1835.5
5,2011,G,10700467.00,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
6,2011,IND,5563779.00,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
7,2011,M,10549548.00,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
8,2011,OUTROS,944699.00,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
9,2011,P,5225163.00,1976.8,906.2,11.6,21.3,15.1,10.7,82.0,54.1,10.2,3.5,559,1734,60,1472.7
14,2012,P,6465573.09,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
12,2012,M,9804192.00,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
13,2012,OUTROS,1519227.00,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
10,2012,G,9501618.00,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
11,2012,IND,4867309.00,1685.8,906.4,10.1,20.6,14.1,9.6,77.6,49.6,10.4,3.5,663,1231,185,785.2
15,2013,G,5145363.10,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
16,2013,IND,6793190.50,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
17,2013,M,15145697.00,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
18,2013,OUTROS,977978.20,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
19,2013,P,16007880.00,1467.6,906.8,11.5,22.3,15.6,10.9,79.2,48.8,10.6,3.5,494,1715,150,1024.9
20,2014,G,5166052.00,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
21,2014,IND,6273227.73,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
22,2014,M,12692373.00,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
23,2014,OUTROS,377336.70,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
24,2014,P,9704383.10,1781.8,906.7,11.6,22.1,15.6,10.8,80.6,51.0,10.8,3.5,601,1697,292,1173.8
28,2015,OUTROS,838831.11,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
27,2015,M,18727187.48,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
29,2015,P,9375881.11,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
25,2015,G,12211695.61,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
26,2015,IND,6607217.22,2260.0,907.0,12.6,22.1,15.9,11.6,83.1,54.8,11.2,3.3,454,1858,125,1499.0
30,2016,G,8671974.30,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
31,2016,IND,10877083.00,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
32,2016,M,20090408.90,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
33,2016,OUTROS,465380.00,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
34,2016,P,16429474.00,2328.7,906.4,13.0,22.0,16.1,12.0,84.3,58.3,10.2,3.2,248,1737,142,1612.1
35,2017,G,19408151.29,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
36,2017,IND,5837368.80,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
37,2017,M,14680425.50,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
38,2017,OUTROS,666907.00,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
39,2017,P,3364829.00,1599.4,906.9,11.5,21.5,15.0,10.5,82.0,52.1,10.9,3.1,708,1855,115,1163.8
44,2018,P,20328977.82,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
42,2018,M,22282487.55,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
43,2018,OUTROS,1155706.00,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
40,2018,G,8424341.00,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
41,2018,IND,8707065.10,1675.8,906.9,12.4,22.5,16.1,11.6,81.8,52.4,11.5,3.3,325,1712,119,1144.0
45,2019,G,14500012.42,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
46,2019,IND,5730985.47,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
47,2019,M,20449473.19,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
48,2019,OUTROS,542250.00,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
49,2019,P,10570722.60,2086.0,907.0,12.6,21.9,15.7,11.5,84.1,56.0,10.4,3.0,655,1836,205,1403.0
54,2020,P,24493976.44,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
53,2020,OUTROS,516340.00,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
51,2020,IND,7715875.00,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
50,2020,G,3474763.00,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
52,2020,M,18390288.21,1879.2,907.0,11.8,22.1,15.3,11.1,78.0,50.2,9.8,3.1,425,1471,222,1378.8
58,2021,OUTROS,483845.00,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6
55,2021,G,15137003.14,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6
56,2021,IND,6858814.00,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6
57,2021,M,25633907.28,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6
59,2021,P,14108126.21,1919.9,906.3,11.8,22.4,15.7,10.9,80.8,50.5,9.8,3.0,527,1565,113,1108.6

# Análise Preditiva - Regressão Linear

## Desenvolvimento, treino e teste do modelo

### G

In [16]:
# Seleção da coluna alvo dos dados referentes ao tamanho da fruta que será utilizado na predição 
# e separação dos dados para treino e teste

alvo = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'G']

y_treino = alvo.loc[df_merge['SAFRA'] != 2021]

y_treino = y_treino.QUANTIDADE_KG

y_teste = alvo.loc[df_merge['SAFRA'] == 2021]

y_teste = y_teste.QUANTIDADE_KG

In [17]:
y_treino # Exibição dos dados alvo de treino

0     11343372.00
5     10700467.00
10     9501618.00
15     5145363.10
20     5166052.00
25    12211695.61
30     8671974.30
35    19408151.29
40     8424341.00
45    14500012.42
50     3474763.00
Name: QUANTIDADE_KG, dtype: float64

In [18]:
y_teste # Exibição dos dados alvo de teste

55    15137003.14
Name: QUANTIDADE_KG, dtype: float64

In [19]:
# Geração e alimentação do dataframe que irá armazenar os dados da predição do tamanho

df_pred_G = pd.DataFrame(columns = ['TAMANHO', 'ÚLT. SAFRA FECHADA', 'SAFRA EM ANDAMENTO', 'QTD. REAL ÚLT. SAFRA FECHADA', 'QTD. PREV. ÚLT. SAFRA FECHADA', 'QTD. PREV. SAFRA EM ANDAMENTO'])

df_pred_G['QTD. REAL ÚLT. SAFRA FECHADA'] = y_teste
df_pred_G['TAMANHO'] = 'G'
df_pred_G['ÚLT. SAFRA FECHADA'] = 2021
df_pred_G['SAFRA EM ANDAMENTO'] = 2022

df_pred_G

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
55,G,2021,2022,15137003.14,NaN,NaN

In [20]:
# Aplicação do SelectKBest para seleção das melhores colunas previsoras dos dados referentes ao tamanho da fruta que 
# será utilizado na predição e separação dos dados para treino e teste

previsores = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'G']

seletor_treino = previsores.loc[df_merge['SAFRA'] != 2021]

seletor_treino = seletor_treino.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

colunas_G = SelectKBest(f_regression, k = 6).fit(seletor_treino, y_treino)

colunas_G = colunas_G.get_support(indices = True)

X_treino = seletor_treino.iloc[:, colunas_G]

seletor_teste = previsores.loc[df_merge['SAFRA'] == 2021]

seletor_teste = seletor_teste.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

X_teste = seletor_teste.iloc[:, colunas_G]

In [21]:
X_treino # Exibição dos dados previsores de treino

,"UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)"
0,82.4,54.6,3.5,633,1921,193
5,82.0,54.1,3.5,559,1734,60
10,77.6,49.6,3.5,663,1231,185
15,79.2,48.8,3.5,494,1715,150
20,80.6,51.0,3.5,601,1697,292
25,83.1,54.8,3.3,454,1858,125
30,84.3,58.3,3.2,248,1737,142
35,82.0,52.1,3.1,708,1855,115
40,81.8,52.4,3.3,325,1712,119
45,84.1,56.0,3.0,655,1836,205
50,78.0,50.2,3.1,425,1471,222

In [22]:
X_teste # Exibição dos dados previsores de teste

,"UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)"
55,80.8,50.5,3.0,527,1565,113

In [23]:
# Execução do treino do modelo

regressao_linear_G = LinearRegression()
regressao_linear_G.fit(X_treino, y_treino)

LinearRegression()

In [24]:
# Execução do teste de predição e exibição do resultado

y_pred_rl = regressao_linear_G.predict(X_teste)

print(y_pred_rl)

[14439197.65823759]

In [25]:
# Cálculo e exibição das métricas de avaliação do modelo

MAPE_rl = np.mean(np.abs((y_teste - y_pred_rl) / y_teste)) * 100
RMSE_rl = mean_squared_error(y_teste, y_pred_rl, squared = False)
print(f"Regressão linear - MAPE (%): {MAPE_rl}")
print(f"Regressão linear - RMSE: {RMSE_rl}")

Regressão linear - MAPE (%): 4.609931538683747
Regressão linear - RMSE: 697805.4817624092

In [26]:
# Alimentação do dataframe com o valor previsto no teste do modelo

y_pred_rl_G = float(y_pred_rl)

y_pred_rl_G = round(y_pred_rl_G, 2)

df_pred_G['QTD. PREV. ÚLT. SAFRA FECHADA'] = y_pred_rl_G

df_pred_G

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
55,G,2021,2022,15137003.14,14439197.66,NaN

### IND

In [27]:
# Seleção da coluna alvo dos dados referentes ao tamanho da fruta que será utilizado na predição 
# e separação dos dados para treino e teste

alvo = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'IND']

y_treino = alvo.loc[df_merge['SAFRA'] != 2021]

y_treino = y_treino.QUANTIDADE_KG

y_teste = alvo.loc[df_merge['SAFRA'] == 2021]

y_teste = y_teste.QUANTIDADE_KG

In [28]:
y_treino # Exibição dos dados alvo de treino

1      5756843.70
6      5563779.00
11     4867309.00
16     6793190.50
21     6273227.73
26     6607217.22
31    10877083.00
36     5837368.80
41     8707065.10
46     5730985.47
51     7715875.00
Name: QUANTIDADE_KG, dtype: float64

In [29]:
y_teste # Exibição dos dados alvo de teste

56    6858814.0
Name: QUANTIDADE_KG, dtype: float64

In [30]:
# Geração e alimentação do dataframe que irá armazenar os dados da predição do tamanho

df_pred_IND = pd.DataFrame(columns = ['TAMANHO', 'ÚLT. SAFRA FECHADA', 'SAFRA EM ANDAMENTO', 'QTD. REAL ÚLT. SAFRA FECHADA', 'QTD. PREV. ÚLT. SAFRA FECHADA', 'QTD. PREV. SAFRA EM ANDAMENTO'])

df_pred_IND['QTD. REAL ÚLT. SAFRA FECHADA'] = y_teste
df_pred_IND['TAMANHO'] = 'IND'
df_pred_IND['ÚLT. SAFRA FECHADA'] = 2021
df_pred_IND['SAFRA EM ANDAMENTO'] = 2022

df_pred_IND

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
56,IND,2021,2022,6858814.0,NaN,NaN

In [31]:
# Aplicação do SelectKBest para seleção das melhores colunas previsoras dos dados referentes ao tamanho da fruta que 
# será utilizado na predição e separação dos dados para treino e teste

previsores = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'IND']

seletor_treino = previsores.loc[df_merge['SAFRA'] != 2021]

seletor_treino = seletor_treino.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

colunas_IND = SelectKBest(f_regression, k = 4).fit(seletor_treino, y_treino)

colunas_IND = colunas_IND.get_support(indices = True)

X_treino = seletor_treino.iloc[:, colunas_IND]

seletor_teste = previsores.loc[df_merge['SAFRA'] == 2021]

seletor_teste = seletor_teste.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

X_teste = seletor_teste.iloc[:, colunas_IND]

In [32]:
X_treino # Exibição dos dados previsores de treino

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
1,12.1,15.5,11.2,633
6,11.6,15.1,10.7,559
11,10.1,14.1,9.6,663
16,11.5,15.6,10.9,494
21,11.6,15.6,10.8,601
26,12.6,15.9,11.6,454
31,13.0,16.1,12.0,248
36,11.5,15.0,10.5,708
41,12.4,16.1,11.6,325
46,12.6,15.7,11.5,655
51,11.8,15.3,11.1,425

In [33]:
X_teste # Exibição dos dados previsores de teste

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
56,11.8,15.7,10.9,527

In [34]:
# Execução do treino do modelo

regressao_linear_IND = LinearRegression()
regressao_linear_IND.fit(X_treino, y_treino)

LinearRegression()

In [35]:
# Execução do teste de predição e exibição do resultado

y_pred_rl = regressao_linear_IND.predict(X_teste)
print(y_pred_rl)

[6937790.74348158]

In [36]:
# Cálculo e exibição das métricas de avaliação do modelo

MAPE_rl = np.mean(np.abs((y_teste - y_pred_rl) / y_teste)) * 100
RMSE_rl = mean_squared_error(y_teste, y_pred_rl, squared = False)
print(f"Regressão linear - MAPE (%): {MAPE_rl}")
print(f"Regressão linear - RMSE: {RMSE_rl}")

Regressão linear - MAPE (%): 1.1514635545092127
Regressão linear - RMSE: 78976.74348157551

In [37]:
# Alimentação do dataframe com o valor previsto no teste do modelo

y_pred_rl_IND = float(y_pred_rl)

y_pred_rl_IND = round(y_pred_rl_IND, 2)

df_pred_IND['QTD. PREV. ÚLT. SAFRA FECHADA'] = y_pred_rl_IND

df_pred_IND

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
56,IND,2021,2022,6858814.0,6937790.74,NaN

### M

In [38]:
# Seleção da coluna alvo dos dados referentes ao tamanho da fruta que será utilizado na predição 
# e separação dos dados para treino e teste

alvo = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'M']

y_treino = alvo.loc[df_merge['SAFRA'] != 2021]

y_treino = y_treino.QUANTIDADE_KG

y_teste = alvo.loc[df_merge['SAFRA'] == 2021]

y_teste = y_teste.QUANTIDADE_KG

In [39]:
y_treino # Exibição dos dados alvo de treino

2      9258368.00
7     10549548.00
12     9804192.00
17    15145697.00
22    12692373.00
27    18727187.48
32    20090408.90
37    14680425.50
42    22282487.55
47    20449473.19
52    18390288.21
Name: QUANTIDADE_KG, dtype: float64

In [40]:
y_teste # Exibição dos dados alvo de teste

57    25633907.28
Name: QUANTIDADE_KG, dtype: float64

In [41]:
# Geração e alimentação do dataframe que irá armazenar os dados da predição do tamanho

df_pred_M = pd.DataFrame(columns = ['TAMANHO', 'ÚLT. SAFRA FECHADA', 'SAFRA EM ANDAMENTO', 'QTD. REAL ÚLT. SAFRA FECHADA', 'QTD. PREV. ÚLT. SAFRA FECHADA', 'QTD. PREV. SAFRA EM ANDAMENTO'])

df_pred_M['QTD. REAL ÚLT. SAFRA FECHADA'] = y_teste
df_pred_M['TAMANHO'] = 'M'
df_pred_M['ÚLT. SAFRA FECHADA'] = 2021
df_pred_M['SAFRA EM ANDAMENTO'] = 2022

df_pred_M

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
57,M,2021,2022,25633907.28,NaN,NaN

In [42]:
# Aplicação do SelectKBest para seleção das melhores colunas previsoras dos dados referentes ao tamanho da fruta que 
# será utilizado na predição e separação dos dados para treino e teste

previsores = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'M']

seletor_treino = previsores.loc[df_merge['SAFRA'] != 2021]

seletor_treino = seletor_treino.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

colunas_M = SelectKBest(mutual_info_regression, k = 6).fit(seletor_treino, y_treino)

colunas_M = colunas_M.get_support(indices = True)

X_treino = seletor_treino.iloc[:, colunas_M]

seletor_teste = previsores.loc[df_merge['SAFRA'] == 2021]

seletor_teste = seletor_teste.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

X_teste = seletor_teste.iloc[:, colunas_M]

In [43]:
X_treino # Exibição dos dados previsores de treino

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
2,12.1,21.8,15.5,11.2,3.5,633
7,11.6,21.3,15.1,10.7,3.5,559
12,10.1,20.6,14.1,9.6,3.5,663
17,11.5,22.3,15.6,10.9,3.5,494
22,11.6,22.1,15.6,10.8,3.5,601
27,12.6,22.1,15.9,11.6,3.3,454
32,13.0,22.0,16.1,12.0,3.2,248
37,11.5,21.5,15.0,10.5,3.1,708
42,12.4,22.5,16.1,11.6,3.3,325
47,12.6,21.9,15.7,11.5,3.0,655
52,11.8,22.1,15.3,11.1,3.1,425

In [44]:
X_teste # Exibição dos dados previsores de teste

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
57,11.8,22.4,15.7,10.9,3.0,527

In [45]:
# Execução do treino do modelo

regressao_linear_M = LinearRegression()
regressao_linear_M.fit(X_treino, y_treino)

LinearRegression()

In [46]:
# Execução do teste de predição e exibição do resultado

y_pred_rl = regressao_linear_M.predict(X_teste)
print(y_pred_rl)

[23606493.89249602]

In [47]:
# Cálculo e exibição das métricas de avaliação do modelo

MAPE_rl = np.mean(np.abs((y_teste - y_pred_rl) / y_teste)) * 100
RMSE_rl = mean_squared_error(y_teste, y_pred_rl, squared = False)
print(f"Regressão linear - MAPE (%): {MAPE_rl}")
print(f"Regressão linear - RMSE: {RMSE_rl}")

Regressão linear - MAPE (%): 7.9091079067989245
Regressão linear - RMSE: 2027413.3875039853

In [48]:
# Alimentação do dataframe com o valor previsto no teste do modelo

y_pred_rl_M = float(y_pred_rl)

y_pred_rl_M = round(y_pred_rl_M, 2)

df_pred_M['QTD. PREV. ÚLT. SAFRA FECHADA'] = y_pred_rl_M

df_pred_M

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
57,M,2021,2022,25633907.28,23606493.89,NaN

### OUTROS

In [49]:
# Seleção da coluna alvo dos dados referentes ao tamanho da fruta que será utilizado na predição 
# e separação dos dados para treino e teste

alvo = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'OUTROS']

y_treino = alvo.loc[df_merge['SAFRA'] != 2021]

y_treino = y_treino.QUANTIDADE_KG

y_teste = alvo.loc[df_merge['SAFRA'] == 2021]

y_teste = y_teste.QUANTIDADE_KG

In [50]:
y_treino # Exibição dos dados alvo de treino

3     1121646.40
8      944699.00
13    1519227.00
18     977978.20
23     377336.70
28     838831.11
33     465380.00
38     666907.00
43    1155706.00
48     542250.00
53     516340.00
Name: QUANTIDADE_KG, dtype: float64

In [51]:
y_teste # Exibição dos dados alvo de teste

58    483845.0
Name: QUANTIDADE_KG, dtype: float64

In [52]:
# Geração e alimentação do dataframe que irá armazenar os dados da predição do tamanho

df_pred_OUTROS = pd.DataFrame(columns = ['TAMANHO', 'ÚLT. SAFRA FECHADA', 'SAFRA EM ANDAMENTO', 'QTD. REAL ÚLT. SAFRA FECHADA', 'QTD. PREV. ÚLT. SAFRA FECHADA', 'QTD. PREV. SAFRA EM ANDAMENTO'])

df_pred_OUTROS['QTD. REAL ÚLT. SAFRA FECHADA'] = y_teste
df_pred_OUTROS['TAMANHO'] = 'OUTROS'
df_pred_OUTROS['ÚLT. SAFRA FECHADA'] = 2021
df_pred_OUTROS['SAFRA EM ANDAMENTO'] = 2022

df_pred_OUTROS

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
58,OUTROS,2021,2022,483845.0,NaN,NaN

In [53]:
# Aplicação do SelectKBest para seleção das melhores colunas previsoras dos dados referentes ao tamanho da fruta que 
# será utilizado na predição e separação dos dados para treino e teste

previsores = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'OUTROS']

seletor_treino = previsores.loc[df_merge['SAFRA'] != 2021]

seletor_treino = seletor_treino.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

colunas_OUTROS = SelectKBest(mutual_info_regression, k = 4).fit(seletor_treino, y_treino)

colunas_OUTROS = colunas_OUTROS.get_support(indices = True)

X_treino = seletor_treino.iloc[:, colunas_OUTROS]

seletor_teste = previsores.loc[df_merge['SAFRA'] == 2021]

seletor_teste = seletor_teste.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

X_teste = seletor_teste.iloc[:, colunas_OUTROS]

In [54]:
X_treino # Exibição dos dados previsores de treino

,"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
3,21.8,82.4,54.6,3.5
8,21.3,82.0,54.1,3.5
13,20.6,77.6,49.6,3.5
18,22.3,79.2,48.8,3.5
23,22.1,80.6,51.0,3.5
28,22.1,83.1,54.8,3.3
33,22.0,84.3,58.3,3.2
38,21.5,82.0,52.1,3.1
43,22.5,81.8,52.4,3.3
48,21.9,84.1,56.0,3.0
53,22.1,78.0,50.2,3.1

In [55]:
X_teste # Exibição dos dados previsores de teste

,"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
58,22.4,80.8,50.5,3.0

In [56]:
# Execução do treino do modelo

regressao_linear_OUTROS = LinearRegression()
regressao_linear_OUTROS.fit(X_treino, y_treino)

LinearRegression()

In [57]:
# Execução do teste de predição e exibição do resultado

y_pred_rl = regressao_linear_OUTROS.predict(X_teste)
print(y_pred_rl)

[503210.5865472]

In [58]:
# Cálculo e exibição das métricas de avaliação do modelo

MAPE_rl = np.mean(np.abs((y_teste - y_pred_rl) / y_teste)) * 100
RMSE_rl = mean_squared_error(y_teste, y_pred_rl, squared = False)
print(f"Regressão linear - MAPE (%): {MAPE_rl}")
print(f"Regressão linear - RMSE: {RMSE_rl}")

Regressão linear - MAPE (%): 4.0024360171536975
Regressão linear - RMSE: 19365.58654719731

In [59]:
# Alimentação do dataframe com o valor previsto no teste do modelo

y_pred_rl_OUTROS = float(y_pred_rl)

y_pred_rl_OUTROS = round(y_pred_rl_OUTROS, 2)

df_pred_OUTROS['QTD. PREV. ÚLT. SAFRA FECHADA'] = y_pred_rl_OUTROS

df_pred_OUTROS

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
58,OUTROS,2021,2022,483845.0,503210.59,NaN

### P

In [60]:
# Seleção da coluna alvo dos dados referentes ao tamanho da fruta que será utilizado na predição 
# e separação dos dados para treino e teste

alvo = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'P']

y_treino = alvo.loc[df_merge['SAFRA'] != 2021]

y_treino = y_treino.QUANTIDADE_KG

y_teste = alvo.loc[df_merge['SAFRA'] == 2021]

y_teste = y_teste.QUANTIDADE_KG

In [61]:
y_treino # Exibição dos dados alvo de treino

4      3110978.00
9      5225163.00
14     6465573.09
19    16007880.00
24     9704383.10
29     9375881.11
34    16429474.00
39     3364829.00
44    20328977.82
49    10570722.60
54    24493976.44
Name: QUANTIDADE_KG, dtype: float64

In [62]:
y_teste # Exibição dos dados alvo de teste

59    14108126.21
Name: QUANTIDADE_KG, dtype: float64

In [63]:
# Geração e alimentação do dataframe que irá armazenar os dados da predição do tamanho

df_pred_P = pd.DataFrame(columns = ['TAMANHO', 'ÚLT. SAFRA FECHADA', 'SAFRA EM ANDAMENTO', 'QTD. REAL ÚLT. SAFRA FECHADA', 'QTD. PREV. ÚLT. SAFRA FECHADA', 'QTD. PREV. SAFRA EM ANDAMENTO'])

df_pred_P['QTD. REAL ÚLT. SAFRA FECHADA'] = y_teste
df_pred_P['TAMANHO'] = 'P'
df_pred_P['ÚLT. SAFRA FECHADA'] = 2021
df_pred_P['SAFRA EM ANDAMENTO'] = 2022

df_pred_P

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
59,P,2021,2022,14108126.21,NaN,NaN

In [64]:
# Aplicação do SelectKBest para seleção das melhores colunas previsoras dos dados referentes ao tamanho da fruta que 
# será utilizado na predição e separação dos dados para treino e teste

previsores = df_merge.loc[df_merge['AGRUPAMENTO_TAMANHO'] == 'P']

seletor_treino = previsores.loc[df_merge['SAFRA'] != 2021]

seletor_treino = seletor_treino.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

colunas_P = SelectKBest(f_regression, k = 4).fit(seletor_treino, y_treino)

colunas_P = colunas_P.get_support(indices = True)

X_treino = seletor_treino.iloc[:, colunas_P]

seletor_teste = previsores.loc[df_merge['SAFRA'] == 2021]

seletor_teste = seletor_teste.iloc[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

X_teste = seletor_teste.iloc[:, colunas_P]

In [65]:
X_treino # Exibição dos dados previsores de treino

,PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
4,905.9,21.8,15.5,633
9,906.2,21.3,15.1,559
14,906.4,20.6,14.1,663
19,906.8,22.3,15.6,494
24,906.7,22.1,15.6,601
29,907.0,22.1,15.9,454
34,906.4,22.0,16.1,248
39,906.9,21.5,15.0,708
44,906.9,22.5,16.1,325
49,907.0,21.9,15.7,655
54,907.0,22.1,15.3,425

In [66]:
X_teste # Exibição dos dados previsores de teste

,PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
59,906.3,22.4,15.7,527

In [67]:
# Execução do treino do modelo

regressao_linear_P = LinearRegression()
regressao_linear_P.fit(X_treino, y_treino)

LinearRegression()

In [68]:
# Execução do teste de predição e exibição do resultado

y_pred_rl = regressao_linear_P.predict(X_teste)
print(y_pred_rl)

[13636277.23756742]

In [69]:
# Cálculo e exibição das métricas de avaliação do modelo

MAPE_rl = np.mean(np.abs((y_teste - y_pred_rl) / y_teste)) * 100
RMSE_rl = mean_squared_error(y_teste, y_pred_rl, squared = False)
print(f"Regressão linear - MAPE (%): {MAPE_rl}")
print(f"Regressão linear - RMSE: {RMSE_rl}")

Regressão linear - MAPE (%): 3.344519076517222
Regressão linear - RMSE: 471848.9724325761

In [70]:
# Alimentação do dataframe com o valor previsto no teste do modelo

y_pred_rl_P = float(y_pred_rl)

y_pred_rl_P = round(y_pred_rl_P, 2)

df_pred_P['QTD. PREV. ÚLT. SAFRA FECHADA'] = y_pred_rl_P

df_pred_P

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
59,P,2021,2022,14108126.21,13636277.24,NaN

## Predição de produção da safra em andamento

### Carga, agrupamento e união dos dados meteorológicos

In [71]:
# Importação dos arquivos CSV dos dados meteorológicos e de produção

file3 = 'C:/Users/*******/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados_Meteorológicos_S_A.csv'
df_meteo_S_A = pd.read_csv(file3, sep = ';')

In [72]:
 # Exibição dos dados meteorológicos
    
df_meteo_S_A.head()

,Unnamed: 0,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)",SAFRA
0,0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
1,1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
2,2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
3,3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
4,4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022

In [73]:
# Seleciona as colunas dos dados meteorológicos que serão utilizadas na análise

df_meteo_S_A = df_meteo_S_A.iloc[:, 2:17]
    
df_meteo_S_A.head() # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)",SAFRA
0,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
1,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
2,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
3,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
4,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022

In [74]:
# Agrupamento dos dados meteorológicos por safra

df_meteo_S_A_group = df_meteo_S_A.groupby('SAFRA').agg({'PRECIPITACAO TOTAL, DIARIO (AUT)(mm)' : 'sum',
                               'PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)' : 'mean',
                               'TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MAXIMA, DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MEDIA, DIARIA (AUT)(°C)' : 'mean',
                               'TEMPERATURA MINIMA, DIARIA (AUT)(°C)' : 'mean',
                               'UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)' : 'mean',
                               'UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)' : 'mean',
                               'VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)' : 'mean',
                               'VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)' : 'mean',
                               'QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)':'sum',
                               'QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)':'sum',
                               'QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)':'sum',
                               'PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)':'sum'})

df_meteo_S_A_group # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
SAFRA,,,,,,,,,,,,,,
2022,1376.6,906.477204,11.379027,22.461398,15.555015,10.766869,79.636474,48.87234,9.654711,2.933131,619,1441,269,926.6

In [75]:
# Realização e visualização do ajuste das casas decimais dos dados

df_meteo_S_A_group['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'] = round(df_meteo_S_A_group['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'], 1)
df_meteo_S_A_group['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'] = round(df_meteo_S_A_group['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'], 1)
df_meteo_S_A_group['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'] = round(df_meteo_S_A_group['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'], 1)
df_meteo_S_A_group['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'] = round(df_meteo_S_A_group['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'], 1)
df_meteo_S_A_group['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'] = round(df_meteo_S_A_group['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'], 1)
df_meteo_S_A_group['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'] = round(df_meteo_S_A_group['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'], 1)
df_meteo_S_A_group['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'] = round(df_meteo_S_A_group['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'], 1)
df_meteo_S_A_group['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'] = round(df_meteo_S_A_group['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'], 1)
df_meteo_S_A_group['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'] = round(df_meteo_S_A_group['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'], 1)

df_meteo_S_A_group # Exibição dos dados

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
SAFRA,,,,,,,,,,,,,,
2022,1376.6,906.5,11.4,22.5,15.6,10.8,79.6,48.9,9.7,2.9,619,1441,269,926.6

In [76]:
# Remoção do índice dos dados

df_meteo_S_A_group = df_meteo_S_A_group.reset_index()

df_meteo_S_A_group # Exibição dos dados

,SAFRA,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
0,2022,1376.6,906.5,11.4,22.5,15.6,10.8,79.6,48.9,9.7,2.9,619,1441,269,926.6

### Aplicação do modelo de predição para cada tamanho da fruta

In [77]:
# Seleção de todas as colunas previsoras

seletor_pred = df_meteo_S_A_group.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]

seletor_pred

,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
0,1376.6,906.5,11.4,22.5,15.6,10.8,79.6,48.9,9.7,2.9,619,1441,269,926.6

#### G

In [78]:
# Seleção das melhores colunas previsoras que foram definidas durante o teste do modelo

X_pred = seletor_pred.iloc[:, colunas_G]

X_pred

,"UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)"
0,79.6,48.9,2.9,619,1441,269

In [79]:
# Execução do modelo de predição e exibição do resultado

y_pred_rl = regressao_linear_G.predict(X_pred)
print(y_pred_rl)

[11362562.17346109]

In [80]:
# Alimentação do dataframe com o valor previsto pelo modelo para a safra em andamento

y_pred_rl_G = float(y_pred_rl)

y_pred_rl_G = round(y_pred_rl_G, 2)

df_pred_G['QTD. PREV. SAFRA EM ANDAMENTO'] = y_pred_rl_G

df_pred_G

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
55,G,2021,2022,15137003.14,14439197.66,11362562.17

In [81]:
# Geração e alimentação do dataframe que irá receber os números da predição de todos os tamanhos da fruta

df_final = df_pred_G

df_final

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
55,G,2021,2022,15137003.14,14439197.66,11362562.17

#### IND

In [82]:
# Seleção das melhores colunas previsoras que foram definidas durante o teste do modelo

X_pred = seletor_pred.iloc[:, colunas_IND]

X_pred

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
0,11.4,15.6,10.8,619

In [83]:
# Execução do modelo de predição e exibição do resultado

y_pred_rl = regressao_linear_IND.predict(X_pred)
print(y_pred_rl)

[5390547.00612453]

In [84]:
# Alimentação do dataframe com o valor previsto pelo modelo para a safra em andamento

y_pred_rl_IND = float(y_pred_rl)

y_pred_rl_IND = round(y_pred_rl_IND, 2)

df_pred_IND['QTD. PREV. SAFRA EM ANDAMENTO'] = y_pred_rl_IND

df_pred_IND

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
56,IND,2021,2022,6858814.0,6937790.74,5390547.01

In [85]:
# Adição dos novos dados de predição no dataframe final

df_final = pd.merge(df_final, df_pred_IND, how = 'outer')

df_final

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
0,G,2021,2022,15137003.14,14439197.66,11362562.17
1,IND,2021,2022,6858814.00,6937790.74,5390547.01

#### M

In [86]:
# Seleção das melhores colunas previsoras que foram definidas durante o teste do modelo

X_pred = seletor_pred.iloc[:, colunas_M]

X_pred

,TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
0,11.4,22.5,15.6,10.8,2.9,619

In [87]:
# Execução do modelo de predição e exibição do resultado

y_pred_rl = regressao_linear_M.predict(X_pred)
print(y_pred_rl)

[28117609.25773685]

In [88]:
# Alimentação do dataframe com o valor previsto pelo modelo para a safra em andamento

y_pred_rl_M = float(y_pred_rl)

y_pred_rl_M = round(y_pred_rl_M, 2)

df_pred_M['QTD. PREV. SAFRA EM ANDAMENTO'] = y_pred_rl_M

df_pred_M

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
57,M,2021,2022,25633907.28,23606493.89,28117609.26

In [89]:
# Adição dos novos dados de predição no dataframe final

df_final = pd.merge(df_final, df_pred_M, how = 'outer')

df_final

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
0,G,2021,2022,15137003.14,14439197.66,11362562.17
1,IND,2021,2022,6858814.00,6937790.74,5390547.01
2,M,2021,2022,25633907.28,23606493.89,28117609.26

#### OUTROS

In [90]:
# Seleção das melhores colunas previsoras que foram definidas durante o teste do modelo

X_pred = seletor_pred.iloc[:, colunas_OUTROS]

X_pred

,"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
0,22.5,79.6,48.9,2.9

In [91]:
# Execução do modelo de predição e exibição do resultado

y_pred_rl = regressao_linear_OUTROS.predict(X_pred)
print(y_pred_rl)

[429189.39211274]

In [92]:
# Alimentação do dataframe com o valor previsto pelo modelo para a safra em andamento

y_pred_rl_OUTROS = float(y_pred_rl)

y_pred_rl_OUTROS = round(y_pred_rl_OUTROS, 2)

df_pred_OUTROS['QTD. PREV. SAFRA EM ANDAMENTO'] = y_pred_rl_OUTROS

df_pred_OUTROS

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
58,OUTROS,2021,2022,483845.0,503210.59,429189.39

In [93]:
# Adição dos novos dados de predição no dataframe final

df_final = pd.merge(df_final, df_pred_OUTROS, how = 'outer')

df_final

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
0,G,2021,2022,15137003.14,14439197.66,11362562.17
1,IND,2021,2022,6858814.00,6937790.74,5390547.01
2,M,2021,2022,25633907.28,23606493.89,28117609.26
3,OUTROS,2021,2022,483845.00,503210.59,429189.39

#### P

In [94]:
# Seleção das melhores colunas previsoras que foram definidas durante o teste do modelo

X_pred = seletor_pred.iloc[:, colunas_P]

X_pred

,PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
0,906.5,22.5,15.6,619

In [95]:
# Execução do modelo de predição e exibição do resultado

y_pred_rl = regressao_linear_P.predict(X_pred)
print(y_pred_rl)

[13239224.11754465]

In [96]:
# Alimentação do dataframe com o valor previsto pelo modelo para a safra em andamento

y_pred_rl_P = float(y_pred_rl)

y_pred_rl_P = round(y_pred_rl_P, 2)

df_pred_P['QTD. PREV. SAFRA EM ANDAMENTO'] = y_pred_rl_P

df_pred_P

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
59,P,2021,2022,14108126.21,13636277.24,13239224.12

In [97]:
# Adição dos novos dados de predição no dataframe final

df_final = pd.merge(df_final, df_pred_P, how = 'outer')

df_final

,TAMANHO,ÚLT. SAFRA FECHADA,SAFRA EM ANDAMENTO,QTD. REAL ÚLT. SAFRA FECHADA,QTD. PREV. ÚLT. SAFRA FECHADA,QTD. PREV. SAFRA EM ANDAMENTO
0,G,2021,2022,15137003.14,14439197.66,11362562.17
1,IND,2021,2022,6858814.00,6937790.74,5390547.01
2,M,2021,2022,25633907.28,23606493.89,28117609.26
3,OUTROS,2021,2022,483845.00,503210.59,429189.39
4,P,2021,2022,14108126.21,13636277.24,13239224.12

In [98]:
# Exportação dos dados da predição para um arquivo .CSV

df_final.to_csv('C:/Users/*******/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados_Predição.csv', sep = ';')

## Armazenamento dos modelos em disco

In [102]:
# Aplicação da função "dump" do módulo "joblib" para cada modelo gerado com o objetivo de armazená-los em disco

dump(regressao_linear_G, 'regressao_linear_G.pkl')
dump(regressao_linear_IND, 'regressao_linear_IND.pkl')
dump(regressao_linear_M, 'regressao_linear_M.pkl')
dump(regressao_linear_OUTROS, 'regressao_linear_OUTROS.pkl')
dump(regressao_linear_P, 'regressao_linear_P.pkl')

['regressao_linear_P.pkl']