In [45]:
# Importação das bibliotecas

import pandas as pd

# Transformação dos dados meteorológicos diários

In [46]:
# Importação do arquivo CSV dos dados meteorológicos diários

file = 'C:/Users/*******/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados Meteorológicos Históricos - Vacaria/Por Dia/dados_A880_D_2021-05-01_2022-03-25.csv'
df = pd.read_csv(file, skiprows = 10, sep = ';')
df.head() # Exibição dos dados

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
0,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.info() # Visualização do tipo de dados de cada coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 11 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Data Medicao                                            329 non-null    object
 1   PRECIPITACAO TOTAL, DIARIO (AUT)(mm)                    314 non-null    object
 2   PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)              317 non-null    object
 3   TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)  317 non-null    object
 4   TEMPERATURA MAXIMA, DIARIA (AUT)(°C)                    317 non-null    object
 5   TEMPERATURA MEDIA, DIARIA (AUT)(°C)                     316 non-null    object
 6   TEMPERATURA MINIMA, DIARIA (AUT)(°C)                    317 non-null    object
 7   UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)           317 non-null    object
 8   UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)          319 non-null    float64
 9   VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)                  318 non-null    object
 10  VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)               317 non-null    object
dtypes: float64(1), object(10)
memory usage: 28.4+ KB

In [48]:
# Substituição de vírgulas por pontos nos dados das colunas com tipo não-numérico

df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'] = df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'].str.replace(',', '.')
df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'] = df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'].str.replace(',', '.')
df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'] = df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'].str.replace(',', '.')
df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'] = df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'].str.replace(',', '.')
df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'] = df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'].str.replace(',', '.')
df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'] = df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'].str.replace(',', '.')
df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'] = df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'].str.replace(',', '.')
df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'] = df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'].str.replace(',', '.')
df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'] = df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'].str.replace(',', '.')

df.head() # Exibição dos dados

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
0,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
# Alteração do tipo de dados das colunas

df['Data Medicao'] = pd.to_datetime(df['Data Medicao'], dayfirst = True)
df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'] = pd.to_numeric(df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'])
df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'] = pd.to_numeric(df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'])
df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'] = pd.to_numeric(df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'])
df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'] = pd.to_numeric(df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'])
df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'] = pd.to_numeric(df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'])
df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'] = pd.to_numeric(df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'])
df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'] = pd.to_numeric(df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'])
df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'] = pd.to_numeric(df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'])
df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'] = pd.to_numeric(df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'])

df.info() # Visualização do tipo de dados de cada coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 11 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Data Medicao                                            329 non-null    datetime64[ns]
 1   PRECIPITACAO TOTAL, DIARIO (AUT)(mm)                    314 non-null    float64
 2   PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)              317 non-null    float64
 3   TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)  317 non-null    float64
 4   TEMPERATURA MAXIMA, DIARIA (AUT)(°C)                    317 non-null    float64
 5   TEMPERATURA MEDIA, DIARIA (AUT)(°C)                     316 non-null    float64
 6   TEMPERATURA MINIMA, DIARIA (AUT)(°C)                    317 non-null    float64
 7   UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)           317 non-null    float64
 8   UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)          319 non-null    float64
 9   VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)                  318 non-null    float64
 10  VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)               317 non-null    float64
dtypes: datetime64[ns](1), float64(10)
memory usage: 28.4 KB

In [50]:
# Realização e visualização do ajuste das casas decimais dos dados

df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'] = round(df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'], 1)
df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'] = round(df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'], 1)
df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'] = round(df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'], 1)
df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'] = round(df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'], 1)
df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'] = round(df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'], 1)

df.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)"
0,2021-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-05-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df.isnull().sum() # identificação de dados faltantes

Data Medicao                                               0
PRECIPITACAO TOTAL, DIARIO (AUT)(mm)                      15
PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)                12
TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)    12
TEMPERATURA MAXIMA, DIARIA (AUT)(°C)                      12
TEMPERATURA MEDIA, DIARIA (AUT)(°C)                       13
TEMPERATURA MINIMA, DIARIA (AUT)(°C)                      12
UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)             12
UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)            10
VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)                    11
VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)                 12
dtype: int64

In [52]:
# Geração e visualização da média dos valores das colunas para utilizar na substituição dos valores nulos

precipitacao_media = df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'].mean()
pressao_atmosf_media = df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'].mean()
temp_orvalho_media = df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'].mean()
temp_maxima_media = df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'].mean()
temp_media_media = df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'].mean()
temp_minima_media = df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'].mean()
umidade_media_media = df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'].mean()
umidade_minima_media = df['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'].mean()
vento_maxima_media = df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'].mean()
vento_media_media = df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'].mean()

print('precipitacao_media: {}'.format(precipitacao_media))
print('pressao_atmosf_media: {}'.format(pressao_atmosf_media))
print('temp_orvalho_media: {}'.format(temp_orvalho_media))
print('temp_maxima_media: {}'.format(temp_maxima_media))
print('temp_media_media: {}'.format(temp_media_media))
print('temp_minima_media: {}'.format(temp_minima_media))
print('umidade_media_media: {}'.format(umidade_media_media))
print('umidade_minima_media: {}'.format(umidade_minima_media))
print('vento_maxima_media: {}'.format(vento_maxima_media))
print('vento_media_media: {}'.format(vento_media_media))

precipitacao_media: 4.18343949044586
pressao_atmosf_media: 906.4763406940064
temp_orvalho_media: 11.378233438485804
temp_maxima_media: 22.45993690851735
temp_media_media: 15.553164556962026
temp_minima_media: 10.765615141955836
umidade_media_media: 79.6378548895899
umidade_minima_media: 48.86833855799373
vento_maxima_media: 9.65314465408805
vento_media_media: 2.9343848580441643

In [53]:
# Realização e visualização do ajuste das casas decimais dos dados

precipitacao_media = round(precipitacao_media, 1)
pressao_atmosf_media = round(pressao_atmosf_media, 1)
temp_orvalho_media = round(temp_orvalho_media, 1)
temp_maxima_media = round(temp_maxima_media, 1)
temp_media_media = round(temp_media_media, 1)
temp_minima_media = round(temp_minima_media, 1)
umidade_media_media = round(umidade_media_media, 1)
umidade_minima_media = round(umidade_minima_media)
vento_maxima_media = round(vento_maxima_media, 1)
vento_media_media = round(vento_media_media, 1)

print('precipitacao_media: {}'.format(precipitacao_media))
print('pressao_atmosf_media: {}'.format(pressao_atmosf_media))
print('temp_orvalho_media: {}'.format(temp_orvalho_media))
print('temp_maxima_media: {}'.format(temp_maxima_media))
print('temp_media_media: {}'.format(temp_media_media))
print('temp_minima_media: {}'.format(temp_minima_media))
print('umidade_media_media: {}'.format(umidade_media_media))
print('umidade_minima_media: {}'.format(umidade_minima_media))
print('vento_maxima_media: {}'.format(vento_maxima_media))
print('vento_media_media: {}'.format(vento_media_media))

precipitacao_media: 4.2
pressao_atmosf_media: 906.5
temp_orvalho_media: 11.4
temp_maxima_media: 22.5
temp_media_media: 15.6
temp_minima_media: 10.8
umidade_media_media: 79.6
umidade_minima_media: 49
vento_maxima_media: 9.7
vento_media_media: 2.9

In [54]:
# Substituição dos dados nulos e verificação se realmente não restou nenhum dado nulo

df.update(df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'].fillna(precipitacao_media))
df.update(df['PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)'].fillna(pressao_atmosf_media))
df.update(df['TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)'].fillna(temp_orvalho_media))
df.update(df['TEMPERATURA MAXIMA, DIARIA (AUT)(°C)'].fillna(temp_maxima_media))
df.update(df['TEMPERATURA MEDIA, DIARIA (AUT)(°C)'].fillna(temp_media_media))
df.update(df['TEMPERATURA MINIMA, DIARIA (AUT)(°C)'].fillna(temp_minima_media))
df.update(df['UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)'].fillna(umidade_media_media))
df.update(df['UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)'].fillna(umidade_minima_media))
df.update(df['VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)'].fillna(vento_maxima_media))
df.update(df['VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)'].fillna(vento_media_media))

df.isnull().sum()

Data Medicao                                              0
PRECIPITACAO TOTAL, DIARIO (AUT)(mm)                      0
PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)                0
TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)    0
TEMPERATURA MAXIMA, DIARIA (AUT)(°C)                      0
TEMPERATURA MEDIA, DIARIA (AUT)(°C)                       0
TEMPERATURA MINIMA, DIARIA (AUT)(°C)                      0
UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)             0
UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)            0
VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)                    0
VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)                 0
dtype: int64

# Transformação dos dados meteorológicos horários

In [55]:
# Importação do arquivo CSV dos dados meteorológicos horários

file = 'C:/Users/*******/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados Meteorológicos Históricos - Vacaria/Por Hora/dados_A880_H_2021-05-01_2022-03-25.csv'
df_hora = pd.read_csv(file, skiprows = 10, sep = ';')
df_hora.head() # Exibição dos dados

,Data Medicao,Hora Medicao,"PRECIPITACAO TOTAL, HORARIO(mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA(mB)","PRESSAO ATMOSFERICA REDUZIDA NIVEL DO MAR, AUT(mB)",PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT)(mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT)(mB),RADIACAO GLOBAL(Kj/m²),TEMPERATURA DA CPU DA ESTACAO(°C),"TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)",...,TEMPERATURA MINIMA NA HORA ANT. (AUT)(°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT)(°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT)(°C),TENSAO DA BATERIA DA ESTACAO(V),UMIDADE REL. MAX. NA HORA ANT. (AUT)(%),UMIDADE REL. MIN. NA HORA ANT. (AUT)(%),"UMIDADE RELATIVA DO AR, HORARIA(%)","VENTO, DIRECAO HORARIA (gr)(° (gr))","VENTO, RAJADA MAXIMA(m/s)","VENTO, VELOCIDADE HORARIA(m/s)"
0,01/05/2021,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/05/2021,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/05/2021,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/05/2021,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/05/2021,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df_hora = df_hora.iloc[:, [0, 9]] # Seleciona as colunas 'Data Medicao' e 'TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'
df_hora.head() # Exibição dos dados

  Data Medicao TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)
0   01/05/2021                                         NaN
1   01/05/2021                                         NaN
2   01/05/2021                                         NaN
3   01/05/2021                                         NaN
4   01/05/2021                                         NaN

In [57]:
df_hora.info() # Visualização do tipo de dados de cada coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7896 entries, 0 to 7895
Data columns (total 2 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Data Medicao                                 7896 non-null   object
 1   TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)  7615 non-null   object
dtypes: object(2)
memory usage: 123.5+ KB

In [58]:
# Substituição de vírgulas por pontos nos dados das colunas com tipo não-numérico

df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'] = df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'].str.replace(',', '.')

df_hora.head() # Exibição dos dados

  Data Medicao TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)
0   01/05/2021                                         NaN
1   01/05/2021                                         NaN
2   01/05/2021                                         NaN
3   01/05/2021                                         NaN
4   01/05/2021                                         NaN

In [59]:
# Alteração do tipo de dados das colunas

df_hora['Data Medicao'] = pd.to_datetime(df_hora['Data Medicao'], dayfirst = True)
df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'] = pd.to_numeric(df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'])

df_hora.info() # Visualização do tipo de dados de cada coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7896 entries, 0 to 7895
Data columns (total 2 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Data Medicao                                 7896 non-null   datetime64[ns]
 1   TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)  7615 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 123.5 KB

In [60]:
df_hora.isnull().sum() # identificação de dados faltantes

Data Medicao                                     0
TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)    281
dtype: int64

In [61]:
# Geração e visualização da média dos valores da coluna que possui dados faltantes para utilizar na substituição dos 
# valores nulos

temp_bulbo_media = df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'].mean()

print('temp_bulbo_media: {}'.format(temp_bulbo_media))

temp_bulbo_media: 15.560091923834536

In [62]:
# Realização e visualização do ajuste das casas decimais dos dados

temp_bulbo_media = round(temp_bulbo_media, 1)

print('temp_bulbo_media: {}'.format(temp_bulbo_media))

temp_bulbo_media: 15.6

In [63]:
# Substituição dos dados nulos e verificação se realmente não restou nenhum dado nulo

df_hora.update(df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'].fillna(temp_bulbo_media))

df_hora.isnull().sum()

Data Medicao                                   0
TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)    0
dtype: int64

In [64]:
# Seleção dos registros com temperatura abaixo de 7.2°C (horas de frio) no ciclo de dormência da planta (Maio a agosto)

df_hora_frio = df_hora.loc[df_hora['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'] < 7.2]

df_hora_frio = df_hora_frio.loc[df_hora_frio['Data Medicao'].dt.month.between(5, 8)]

df_hora_frio # Exibição dos dados

     Data Medicao  TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)
288    2021-05-13                                          7.1
289    2021-05-13                                          5.9
290    2021-05-13                                          5.7
291    2021-05-13                                          5.5
292    2021-05-13                                          3.0
...           ...                                          ...
2862   2021-08-28                                          7.0
2863   2021-08-28                                          6.4
2864   2021-08-28                                          6.1
2865   2021-08-28                                          6.5
2866   2021-08-28                                          6.2

[619 rows x 2 columns]

In [65]:
# Contagem/agrupamento das horas de frio diárias e alteração do nome da coluna

df_hora_frio = df_hora_frio.groupby(['Data Medicao']).count()

df_hora_frio.rename(columns = {'TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)': 'QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)'}, inplace = True)

df_hora_frio.head()

              QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)
Data Medicao
2021-05-13                                                   13
2021-05-14                                                    9
2021-05-15                                                    4
2021-05-18                                                    5
2021-05-19                                                    8

In [66]:
# União do dataset com o número diário de horas de frio com o dataset dos dados meteorológicos diários

df = pd.merge(df, df_hora_frio, how = 'outer', on = 'Data Medicao').sort_values(by = 'Data Medicao')

In [67]:
# Substituição dos dados nulos pelo número 0 na coluna das horas de frio

df.update(df['QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)'].fillna(0))

In [68]:
# Alteração do tipo de dados da coluna das horas de frio para número inteiro e exibição da alteração

df['QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)'] = pd.to_numeric(df['QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)'], downcast = 'integer')
df.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)"
0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0
1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0
2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0
3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0
4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0

In [69]:
# Seleção dos registros de temperatura do ciclo vegetativo da planta (Setembro a abril)

df_hora_tempcv = df_hora.loc[df_hora['Data Medicao'].dt.month.isin([1, 2, 3, 4, 9, 10, 11, 12])]

df_hora_tempcv # Exibição dos dados

     Data Medicao  TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)
2952   2021-09-01                                         12.1
2953   2021-09-01                                         11.8
2954   2021-09-01                                         11.3
2955   2021-09-01                                         10.8
2956   2021-09-01                                         10.9
...           ...                                          ...
7891   2022-03-25                                         16.4
7892   2022-03-25                                         16.8
7893   2022-03-25                                         15.2
7894   2022-03-25                                         14.1
7895   2022-03-25                                         12.6

[4944 rows x 2 columns]

In [70]:
# Contagem/agrupamento das horas de temperatura ideal para o ciclo vegetativo (18°C a 23 C°) e alteração do nome da coluna

df_hora_idealcv = df_hora_tempcv[df_hora_tempcv['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'].between(18, 23)]

df_hora_idealcv = df_hora_idealcv.groupby(['Data Medicao']).count()

df_hora_idealcv.rename(columns = {'TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)': 'QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)'}, inplace = True)

df_hora_idealcv.head()

              QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)
Data Medicao
2021-09-01                                                    8
2021-09-02                                                    7
2021-09-03                                                   10
2021-09-04                                                    5
2021-09-05                                                    8

In [71]:
# União do dataset com o número diário de horas de temperatura ideal para o ciclo vegetativo com o dataset dos dados meteorológicos diários

df = pd.merge(df, df_hora_idealcv, how = 'outer', on = 'Data Medicao').sort_values(by = 'Data Medicao')

In [72]:
# Substituição dos dados nulos pelo número 0 na coluna das horas de temperatura ideal para o ciclo vegetativo

df.update(df['QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)'].fillna(0))

In [73]:
# Alteração do tipo de dados da coluna das horas de temperatura ideal para o ciclo vegetativo para número inteiro e exibição da alteração

df['QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)'] = pd.to_numeric(df['QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)'], downcast = 'integer')
df.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)"
0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0
1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0
2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0
3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0
4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0

In [74]:
# Contagem/agrupamento das horas de temperatura prejudicial para o ciclo vegetativo (> 27 C°) e alteração do nome da coluna

df_hora_prejucv = df_hora_tempcv[df_hora_tempcv['TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)'] > 27]

df_hora_prejucv = df_hora_prejucv.groupby(['Data Medicao']).count()

df_hora_prejucv.rename(columns = {'TEMPERATURA DO AR - BULBO SECO, HORARIA(°C)': 'QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)'}, inplace = True)

df_hora_prejucv.head()

              QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)
Data Medicao
2021-09-20                                                    2
2021-09-27                                                    1
2021-10-27                                                    2
2021-11-02                                                    1
2021-11-05                                                    3

In [75]:
# União do dataset com o número diário de horas de temperatura prejudicial para o ciclo vegetativo com o dataset dos dados meteorológicos diários

df = pd.merge(df, df_hora_prejucv, how = 'outer', on = 'Data Medicao').sort_values(by = 'Data Medicao')

In [76]:
# Substituição dos dados nulos pelo número 0 na coluna das horas de temperatura prejudicial para o ciclo vegetativo

df.update(df['QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)'].fillna(0))

In [77]:
# Alteração do tipo de dados da coluna das horas de temperatura prejudicial para o ciclo vegetativo para número inteiro e exibição da alteração

df['QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)'] = pd.to_numeric(df['QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)'], downcast = 'integer')
df.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)"
0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0
1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0
2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0
3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0
4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0

In [78]:
# Seleção dos registros de precipitação do ciclo vegetativo da planta (Setembro a abril)

df_prec_veg = df.loc[df['Data Medicao'].dt.month.isin([1, 2, 3, 4, 9, 10, 11, 12])]

df_prec_veg # Exibição dos dados

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)"
123,2021-09-01,0.0,910.6,10.5,23.2,15.4,9.8,75.2,42.0,13.0,4.8,0,8,0
124,2021-09-02,0.0,907.9,11.1,23.9,16.6,11.2,73.8,38.0,9.8,3.4,0,7,0
125,2021-09-03,0.0,905.8,12.4,23.5,17.0,11.4,76.2,50.0,7.4,2.1,0,10,0
126,2021-09-04,0.0,905.3,11.9,24.8,14.9,7.7,85.6,32.0,12.3,1.8,0,5,0
127,2021-09-05,2.2,904.9,14.0,21.8,16.3,11.7,87.5,61.0,10.4,3.1,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,2022-03-21,0.0,911.6,11.8,21.7,15.4,10.5,80.1,61.0,10.2,3.7,0,7,0
325,2022-03-22,0.0,909.0,12.9,23.2,16.7,12.2,79.7,54.0,13.9,5.5,0,8,0
326,2022-03-23,0.0,905.5,14.2,19.8,15.9,14.0,89.5,77.0,12.1,4.8,0,3,0
327,2022-03-24,31.4,900.8,16.1,18.8,16.7,15.3,96.5,84.0,15.0,4.9,0,5,0
328,2022-03-25,2.8,901.3,14.6,18.1,15.2,13.9,96.1,82.0,11.9,3.7,0,0,0

In [79]:
df_prec_veg = df_prec_veg.iloc[:, [0, 1]] # Seleciona as colunas 'Data Medicao' e 'PRECIPITACAO TOTAL, DIARIO (AUT)(mm)'
df_prec_veg.head() # Exibição dos dados

    Data Medicao  PRECIPITACAO TOTAL, DIARIO (AUT)(mm)
123   2021-09-01                                   0.0
124   2021-09-02                                   0.0
125   2021-09-03                                   0.0
126   2021-09-04                                   0.0
127   2021-09-05                                   2.2

In [ ]:
df_prec_veg.rename(columns = {'PRECIPITACAO TOTAL, DIARIO (AUT)(mm)': 'PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)'}, inplace = True)

df_prec_veg.head()

In [81]:
# União do dataset com a precipitação do ciclo vegetativo da planta com o dataset dos dados meteorológicos diários

df = pd.merge(df, df_prec_veg, how = 'outer', on = 'Data Medicao').sort_values(by = 'Data Medicao')

In [82]:
# Substituição dos dados nulos pelo número 0 na coluna da precipitação do ciclo vegetativo da planta

df.update(df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)'].fillna(0))

In [83]:
# Alteração do tipo de dados da coluna da precipitação do ciclo vegetativo da planta para número inteiro e exibição da alteração

df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)'] = pd.to_numeric(df['PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)'], downcast = 'integer')
df.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)"
0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0
1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0
2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0
3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0
4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0

In [84]:
# Geração de uma nova coluna que indica a que safra o registro pertence (É considerado como ano agrícola o período entre 
# 01 de maio até 30 de abril do próximo ano)

for index, row in df.iterrows():
    if df.loc[index, 'Data Medicao'].month in (1, 2, 3, 4):
        df.loc[index, 'SAFRA'] = str(df.loc[index, 'Data Medicao'].year)
    else:
        df.loc[index, 'SAFRA'] = str(df.loc[index, 'Data Medicao'].year + 1)
    
df.head() # Exibição dos dados

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB),TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","TEMPERATURA MINIMA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)","UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)","VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)","VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)","QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)","QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)","QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)","PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)",SAFRA
0,2021-05-01,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
1,2021-05-02,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
2,2021-05-03,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
3,2021-05-04,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022
4,2021-05-05,4.2,906.5,11.4,22.5,15.6,10.8,79.6,49.0,9.7,2.9,0,0,0,0.0,2022

In [85]:
# Visualização do tipo de dados de cada coluna

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329 entries, 0 to 328
Data columns (total 16 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Data Medicao                                                          329 non-null    datetime64[ns]
 1   PRECIPITACAO TOTAL, DIARIO (AUT)(mm)                                  329 non-null    float64
 2   PRESSAO ATMOSFERICA MEDIA DIARIA (AUT)(mB)                            329 non-null    float64
 3   TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C)                329 non-null    float64
 4   TEMPERATURA MAXIMA, DIARIA (AUT)(°C)                                  329 non-null    float64
 5   TEMPERATURA MEDIA, DIARIA (AUT)(°C)                                   329 non-null    float64
 6   TEMPERATURA MINIMA, DIARIA (AUT)(°C)                                  329 non-null    float64
 7   UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)                         329 non-null    float64
 8   UMIDADE RELATIVA DO AR, MINIMA DIARIA (AUT)(%)                        329 non-null    float64
 9   VENTO, RAJADA MAXIMA DIARIA (AUT)(m/s)                                329 non-null    float64
 10  VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)                             329 non-null    float64
 11  QTD. DE HORAS DE FRIO (< 7.2°C), DIARIA (MAIO - AGOSTO)               329 non-null    int8
 12  QTD. DE HORAS TEMP. IDEAL (18°C - 23 C°), DIARIA (SETEMBRO - ABRIL)   329 non-null    int8
 13  QTD. DE HORAS TEMP. PREJUDICIAL (> 27 C°), DIARIA (SETEMBRO - ABRIL)  329 non-null    int8
 14  PRECIPITACAO TOTAL, DIARIO (AUT)(mm) (SETEMBRO - ABRIL)               329 non-null    float64
 15  SAFRA                                                                 329 non-null    object
dtypes: datetime64[ns](1), float64(11), int8(3), object(1)
memory usage: 45.0+ KB

In [86]:
# Exportação dos dados transformados para um arquivo .CSV

df.to_csv('C:/Users/*********/Documents/Projetos Jupyter Notebook/TCC - Ciência de Dados/Dados_Meteorológicos_S_A.csv', sep = ';')